"""
Sample email data for training the email topic classifier.
This file contains a large collection of labeled email examples for each topic.
"""

SAMPLE_EMAILS = [
    # Work (25 examples)
    ("Meeting scheduled for tomorrow at 2 PM to discuss project timeline", "work"),
    ("Please review the attached quarterly report", "work"),
    ("Your job application has been received", "work"),
    ("Team building event this Friday", "work"),
    ("Project deadline extended to next month", "work"),
    ("New software update for your work computer", "work"),
    ("Please complete the employee survey", "work"),
    ("Your performance review is scheduled", "work"),
    ("Office will be closed for maintenance", "work"),
    ("New team member joining next week", "work"),
    ("Please submit your timesheet by Friday", "work"),
    ("Quarterly business review meeting", "work"),
    ("New project kickoff meeting", "work"),
    ("Client presentation tomorrow", "work"),
    ("Team standup meeting at 10 AM", "work"),
    ("Annual performance evaluation", "work"),
    ("New company policy announcement", "work"),
    ("Department restructuring update", "work"),
    ("Training session registration", "work"),
    ("Work from home policy update", "work"),
    ("New office location announcement", "work"),
    ("Employee benefits enrollment", "work"),
    ("Company-wide town hall meeting", "work"),
    ("New software license agreement", "work"),
    ("Emergency maintenance notification", "work"),

    # Shipping (25 examples)
    ("Your package has been shipped", "shipping"),
    ("Order #12345 is out for delivery", "shipping"),
    ("Tracking number for your shipment", "shipping"),
    ("Package delivered to your doorstep", "shipping"),
    ("Shipping confirmation for your order", "shipping"),
    ("Your order has left our warehouse", "shipping"),
    ("Delivery attempt was made", "shipping"),
    ("Package is in transit", "shipping"),
    ("Shipping label created", "shipping"),
    ("Estimated delivery date update", "shipping"),
    ("Your package is at the local facility", "shipping"),
    ("International shipping update", "shipping"),
    ("Return shipping label attached", "shipping"),
    ("Express shipping confirmation", "shipping"),
    ("Package arrived at sorting facility", "shipping"),
    ("Customs clearance update", "shipping"),
    ("Package held at customs", "shipping"),
    ("Delivery exception notification", "shipping"),
    ("Signature required for delivery", "shipping"),
    ("Package rerouted to new address", "shipping"),
    ("Shipping delay notification", "shipping"),
    ("Package weight verification", "shipping"),
    ("International shipping documentation", "shipping"),
    ("Bulk shipping confirmation", "shipping"),
    ("Shipping insurance confirmation", "shipping"),

    # Finance (25 examples)
    ("Your bank statement is ready", "finance"),
    ("Credit card payment due", "finance"),
    ("Investment portfolio update", "finance"),
    ("Mortgage payment confirmation", "finance"),
    ("Tax filing reminder", "finance"),
    ("Stock market update", "finance"),
    ("Insurance policy renewal", "finance"),
    ("Retirement account statement", "finance"),
    ("Loan application status", "finance"),
    ("Budget report for the month", "finance"),
    ("Direct deposit confirmation", "finance"),
    ("Credit score update", "finance"),
    ("Investment opportunity alert", "finance"),
    ("Bill payment reminder", "finance"),
    ("Financial statement available", "finance"),
    ("Dividend payment notification", "finance"),
    ("Stock split announcement", "finance"),
    ("Mutual fund performance report", "finance"),
    ("401(k) contribution update", "finance"),
    ("Interest rate change notification", "finance"),
    ("Foreign exchange rate alert", "finance"),
    ("Investment portfolio rebalancing", "finance"),
    ("Financial planning consultation", "finance"),
    ("Wealth management report", "finance"),
    ("Financial market analysis", "finance"),

    # Travel (25 examples)
    ("Flight booking confirmation", "travel"),
    ("Hotel reservation details", "travel"),
    ("Travel insurance information", "travel"),
    ("Car rental confirmation", "travel"),
    ("Vacation package details", "travel"),
    ("Travel itinerary update", "travel"),
    ("Airport transfer booking", "travel"),
    ("Travel visa application", "travel"),
    ("Cruise booking confirmation", "travel"),
    ("Travel advisory update", "travel"),
    ("Flight delay notification", "travel"),
    ("Gate change information", "travel"),
    ("Baggage claim details", "travel"),
    ("Travel rewards update", "travel"),
    ("Airport parking reservation", "travel"),
    ("Travel itinerary changes", "travel"),
    ("Airport lounge access", "travel"),
    ("Travel document verification", "travel"),
    ("Travel health advisory", "travel"),
    ("Travel weather alert", "travel"),
    ("Travel booking cancellation", "travel"),
    ("Travel package upgrade", "travel"),
    ("Travel loyalty points", "travel"),
    ("Travel booking modification", "travel"),
    ("Travel emergency contact", "travel"),

    # Promotions (25 examples)
    ("Special offer: 50% off", "promotions"),
    ("Flash sale starts now", "promotions"),
    ("Limited time discount", "promotions"),
    ("Buy one get one free", "promotions"),
    ("Holiday special deals", "promotions"),
    ("Member exclusive offer", "promotions"),
    ("Seasonal sale announcement", "promotions"),
    ("New product launch discount", "promotions"),
    ("Referral bonus program", "promotions"),
    ("Loyalty rewards update", "promotions"),
    ("Early access to sale", "promotions"),
    ("Birthday special discount", "promotions"),
    ("Clearance sale alert", "promotions"),
    ("New customer discount", "promotions"),
    ("Holiday bundle offer", "promotions"),
    ("Weekend special deals", "promotions"),
    ("Student discount offer", "promotions"),
    ("Military discount program", "promotions"),
    ("Senior citizen special", "promotions"),
    ("First-time buyer offer", "promotions"),
    ("Bundle and save promotion", "promotions"),
    ("Flash deal alert", "promotions"),
    ("Limited edition offer", "promotions"),
    ("Seasonal clearance sale", "promotions"),
    ("Holiday gift guide", "promotions"),

    # Social (25 examples)
    ("Friend request on social media", "social"),
    ("Social event invitation", "social"),
    ("Group chat message", "social"),
    ("Social media notification", "social"),
    ("Community event announcement", "social"),
    ("Social gathering details", "social"),
    ("Social media account update", "social"),
    ("Social networking event", "social"),
    ("Social media post comment", "social"),
    ("Social group activity", "social"),
    ("New connection request", "social"),
    ("Social media milestone", "social"),
    ("Group event reminder", "social"),
    ("Social media mention", "social"),
    ("Community update", "social"),
    ("Social media challenge", "social"),
    ("Online community event", "social"),
    ("Social media campaign", "social"),
    ("Virtual meetup invitation", "social"),
    ("Social media contest", "social"),
    ("Community fundraiser", "social"),
    ("Social media workshop", "social"),
    ("Online networking event", "social"),
    ("Social media webinar", "social"),
    ("Community volunteer opportunity", "social"),

    # Updates (25 examples)
    ("System maintenance update", "updates"),
    ("Software version update", "updates"),
    ("Account settings changed", "updates"),
    ("Policy update notification", "updates"),
    ("Service status update", "updates"),
    ("Platform changes announcement", "updates"),
    ("Feature update notification", "updates"),
    ("Security update required", "updates"),
    ("Terms of service update", "updates"),
    ("Product update information", "updates"),
    ("App update available", "updates"),
    ("Firmware update required", "updates"),
    ("Database maintenance notice", "updates"),
    ("System upgrade scheduled", "updates"),
    ("Version release notes", "updates"),
    ("API update notification", "updates"),
    ("Security patch release", "updates"),
    ("Platform maintenance", "updates"),
    ("Service interruption notice", "updates"),
    ("Feature deprecation notice", "updates"),
    ("System configuration update", "updates"),
    ("Performance update", "updates"),
    ("Compatibility update", "updates"),
    ("Interface update", "updates"),
    ("Backend system update", "updates"),

    # Support (25 examples)
    ("Technical support ticket", "support"),
    ("Customer service response", "support"),
    ("Help desk ticket update", "support"),
    ("Product support information", "support"),
    ("Service request status", "support"),
    ("Support ticket resolution", "support"),
    ("Customer care update", "support"),
    ("Technical assistance", "support"),
    ("Support case update", "support"),
    ("Customer service feedback", "support"),
    ("Issue resolution update", "support"),
    ("Support chat transcript", "support"),
    ("Knowledge base article", "support"),
    ("Troubleshooting guide", "support"),
    ("Support survey request", "support"),
    ("Technical issue resolution", "support"),
    ("Product troubleshooting", "support"),
    ("Service recovery update", "support"),
    ("Support ticket escalation", "support"),
    ("Technical documentation", "support"),
    ("Product usage guide", "support"),
    ("Service restoration", "support"),
    ("Technical consultation", "support"),
    ("Product maintenance guide", "support"),
    ("Service optimization", "support"),

    # Spam (25 examples)
    ("Win a free iPhone", "spam"),
    ("Urgent: Your account is locked", "spam"),
    ("You've won a lottery", "spam"),
    ("Click here to claim prize", "spam"),
    ("Urgent: Verify your account", "spam"),
    ("You've been selected", "spam"),
    ("Claim your reward now", "spam"),
    ("Urgent: Action required", "spam"),
    ("You're a winner", "spam"),
    ("Limited time offer", "spam"),
    ("Congratulations! You've won", "spam"),
    ("Your account needs verification", "spam"),
    ("Claim your inheritance", "spam"),
    ("Urgent: Security alert", "spam"),
    ("You've been chosen", "spam"),
    ("Exclusive offer for you", "spam"),
    ("Your account is at risk", "spam"),
    ("Claim your prize now", "spam"),
    ("Urgent: Account suspension", "spam"),
    ("You're a lucky winner", "spam"),
    ("Special offer just for you", "spam"),
    ("Your account needs attention", "spam"),
    ("Claim your reward today", "spam"),
    ("Urgent: Action needed", "spam"),
    ("You've been selected as winner", "spam"),

    # Events (25 examples)
    ("Conference registration", "events"),
    ("Webinar invitation", "events"),
    ("Event ticket confirmation", "events"),
    ("Workshop registration", "events"),
    ("Seminar details", "events"),
    ("Event schedule update", "events"),
    ("Conference agenda", "events"),
    ("Event reminder", "events"),
    ("Workshop materials", "events"),
    ("Event feedback request", "events"),
    ("Virtual event login details", "events"),
    ("Event cancellation notice", "events"),
    ("Event venue change", "events"),
    ("Event speaker announcement", "events"),
    ("Event registration confirmation", "events"),
    ("Event schedule changes", "events"),
    ("Event materials download", "events"),
    ("Event networking session", "events"),
    ("Event breakout rooms", "events"),
    ("Event Q&A session", "events"),
    ("Event panel discussion", "events"),
    ("Event keynote speaker", "events"),
    ("Event workshop materials", "events"),
    ("Event networking guide", "events"),
    ("Event technical requirements", "events")
] 