"""
Sample email data for training the email topic classifier.
This file contains a large collection of labeled email examples for each topic.
"""

SAMPLE_EMAILS = [
    # Work category - Added more job/internship related examples
    ("Your job application has been received", "work"),
    ("Interview scheduled for Software Engineer position", "work"),
    ("Internship opportunity at Tech Company", "work"),
    ("Job offer for Senior Developer role", "work"),
    ("Application status update for Data Scientist position", "work"),
    ("Technical interview preparation guide", "work"),
    ("Welcome to your new role at Company", "work"),
    ("Performance review meeting scheduled", "work"),
    ("Team meeting agenda for tomorrow", "work"),
    ("Project deadline extension request", "work"),
    ("New employee onboarding schedule", "work"),
    ("Career development workshop invitation", "work"),
    ("Job fair registration confirmation", "work"),
    ("Recruitment process update", "work"),
    ("Interview feedback for Product Manager role", "work"),
    ("Internship program application deadline", "work"),
    ("Job application status: Under Review", "work"),
    ("Technical assessment instructions", "work"),
    ("Welcome to the interview process", "work"),
    ("Job offer details and next steps", "work"),
    ("Internship program orientation", "work"),
    ("Career fair registration", "work"),
    ("Job application confirmation", "work"),
    ("Interview scheduling for Engineering role", "work"),
    ("New grad program application status", "work"),

    # Promotions category - Added more diverse promotion examples
    ("50% off on all electronics", "promotions"),
    ("Flash sale: Up to 70% off", "promotions"),
    ("Limited time offer: Buy 1 Get 1 Free", "promotions"),
    ("Special discount for loyal customers", "promotions"),
    ("Holiday season sale starts now", "promotions"),
    ("Exclusive member-only deals", "promotions"),
    ("Weekend special: 30% off everything", "promotions"),
    ("Clearance sale: Up to 80% off", "promotions"),
    ("New customer discount: 20% off", "promotions"),
    ("Seasonal promotion: Spring collection", "promotions"),
    ("Refer a friend and get $20 off", "promotions"),
    ("Birthday special: Extra 15% off", "promotions"),
    ("Black Friday early access", "promotions"),
    ("Cyber Monday deals preview", "promotions"),
    ("Membership rewards points bonus", "promotions"),
    ("Exclusive online-only offers", "promotions"),
    ("Limited edition product launch", "promotions"),
    ("Premium member exclusive sale", "promotions"),
    ("Flash deal: 24 hours only", "promotions"),
    ("Special bundle offers", "promotions"),
    ("Holiday gift guide with discounts", "promotions"),
    ("Early access to summer sale", "promotions"),
    ("Reward points multiplier event", "promotions"),
    ("Special pricing for newsletter subscribers", "promotions"),
    ("Limited time bundle deals", "promotions"),

    # Shipping examples
    ("Your package has been delivered", "shipping"),
    ("Order #12345 has been shipped", "shipping"),
    ("Tracking update for your delivery", "shipping"),
    ("Package out for delivery", "shipping"),
    ("Shipping confirmation for order #67890", "shipping"),
    ("Delivery attempt failed", "shipping"),
    ("Your order is in transit", "shipping"),
    ("Package arrived at local facility", "shipping"),
    ("Shipping label created", "shipping"),
    ("Return shipping instructions", "shipping"),
    ("International shipping update", "shipping"),
    ("Customs clearance completed", "shipping"),
    ("Express delivery confirmation", "shipping"),
    ("Package delayed in transit", "shipping"),
    ("Shipping address verification", "shipping"),
    ("Delivery route update", "shipping"),
    ("Package pickup scheduled", "shipping"),
    ("Shipping insurance confirmation", "shipping"),
    ("Bulk shipping notification", "shipping"),
    ("Shipping method upgrade", "shipping"),
    ("Delivery time window update", "shipping"),
    ("Shipping partner change", "shipping"),
    ("Package consolidation notice", "shipping"),
    ("Shipping hold request", "shipping"),
    ("Delivery preferences update", "shipping"),

    # Finance examples
    ("Your monthly statement is ready", "finance"),
    ("Payment confirmation for invoice #123", "finance"),
    ("Account balance alert", "finance"),
    ("Transaction failed notification", "finance"),
    ("Credit card payment due", "finance"),
    ("Investment portfolio update", "finance"),
    ("Bank statement available", "finance"),
    ("Payment received confirmation", "finance"),
    ("Account security alert", "finance"),
    ("Direct deposit notification", "finance"),
    ("Credit score update", "finance"),
    ("Loan payment reminder", "finance"),
    ("Investment opportunity", "finance"),
    ("Tax document available", "finance"),
    ("Refund processed", "finance"),
    ("Account verification required", "finance"),
    ("Payment method update", "finance"),
    ("Transaction limit alert", "finance"),
    ("Investment performance report", "finance"),
    ("Credit limit increase", "finance"),
    ("Account fee notification", "finance"),
    ("Payment plan confirmation", "finance"),
    ("Financial statement ready", "finance"),
    ("Transaction dispute update", "finance"),
    ("Account closure confirmation", "finance"),

    # Travel examples
    ("Flight booking confirmation", "travel"),
    ("Hotel reservation details", "travel"),
    ("Car rental confirmation", "travel"),
    ("Travel insurance policy", "travel"),
    ("Flight status update", "travel"),
    ("Hotel check-in reminder", "travel"),
    ("Travel itinerary update", "travel"),
    ("Airport transfer booking", "travel"),
    ("Travel visa application", "travel"),
    ("Flight delay notification", "travel"),
    ("Hotel cancellation policy", "travel"),
    ("Travel package confirmation", "travel"),
    ("Airport parking reservation", "travel"),
    ("Travel advisory update", "travel"),
    ("Flight cancellation notice", "travel"),
    ("Hotel upgrade available", "travel"),
    ("Travel rewards points", "travel"),
    ("Airport lounge access", "travel"),
    ("Travel document reminder", "travel"),
    ("Flight rebooking options", "travel"),
    ("Hotel loyalty program", "travel"),
    ("Travel credit card offer", "travel"),
    ("Airport security update", "travel"),
    ("Travel package deal", "travel"),
    ("Flight seat selection", "travel"),

    # Social examples
    ("New connection request", "social"),
    ("Event invitation from friend", "social"),
    ("Social media notification", "social"),
    ("Group chat message", "social"),
    ("Profile update reminder", "social"),
    ("Friend request accepted", "social"),
    ("Social media milestone", "social"),
    ("Event RSVP reminder", "social"),
    ("Social network update", "social"),
    ("Group event planning", "social"),
    ("Social media alert", "social"),
    ("Friend birthday reminder", "social"),
    ("Social network suggestion", "social"),
    ("Event photo tag", "social"),
    ("Social media mention", "social"),
    ("Group activity update", "social"),
    ("Social network feature", "social"),
    ("Event check-in", "social"),
    ("Social media trend", "social"),
    ("Friend activity update", "social"),
    ("Social network achievement", "social"),
    ("Event memory reminder", "social"),
    ("Social media challenge", "social"),
    ("Group membership update", "social"),
    ("Social network milestone", "social"),

    # Updates examples
    ("System maintenance notice", "updates"),
    ("Software update available", "updates"),
    ("Account settings changed", "updates"),
    ("Policy update notification", "updates"),
    ("Service status update", "updates"),
    ("Website maintenance", "updates"),
    ("App update required", "updates"),
    ("Security patch available", "updates"),
    ("Terms of service update", "updates"),
    ("Privacy policy changes", "updates"),
    ("Feature update announcement", "updates"),
    ("System upgrade notice", "updates"),
    ("Account update required", "updates"),
    ("Service interruption", "updates"),
    ("Maintenance schedule", "updates"),
    ("Update installation guide", "updates"),
    ("System requirements update", "updates"),
    ("Service improvement notice", "updates"),
    ("Update rollback notice", "updates"),
    ("Feature deprecation notice", "updates"),
    ("Update installation failed", "updates"),
    ("System compatibility update", "updates"),
    ("Update verification required", "updates"),
    ("Service restoration notice", "updates"),
    ("Update installation complete", "updates"),

    # Support examples
    ("Technical support ticket", "support"),
    ("Customer service response", "support"),
    ("Help desk ticket update", "support"),
    ("Support request received", "support"),
    ("Issue resolution update", "support"),
    ("Technical assistance", "support"),
    ("Customer support follow-up", "support"),
    ("Support ticket closed", "support"),
    ("Help request confirmation", "support"),
    ("Support case update", "support"),
    ("Technical issue resolved", "support"),
    ("Customer service survey", "support"),
    ("Support ticket escalation", "support"),
    ("Help desk response", "support"),
    ("Support request status", "support"),
    ("Technical support follow-up", "support"),
    ("Customer service feedback", "support"),
    ("Support ticket reopened", "support"),
    ("Help request update", "support"),
    ("Support case resolution", "support"),
    ("Technical support survey", "support"),
    ("Customer service update", "support"),
    ("Support ticket status", "support"),
    ("Help desk follow-up", "support"),
    ("Support request resolved", "support"),

    # Spam examples
    ("You've won a lottery", "spam"),
    ("Urgent money transfer needed", "spam"),
    ("Account security alert", "spam"),
    ("Inheritance claim", "spam"),
    ("Nigerian prince email", "spam"),
    ("Password reset request", "spam"),
    ("Account verification needed", "spam"),
    ("Suspicious login attempt", "spam"),
    ("Payment confirmation", "spam"),
    ("Account suspended", "spam"),
    ("Urgent action required", "spam"),
    ("Security breach alert", "spam"),
    ("Account compromise", "spam"),
    ("Payment failed", "spam"),
    ("Account locked", "spam"),
    ("Security verification", "spam"),
    ("Account access required", "spam"),
    ("Payment processing", "spam"),
    ("Account update needed", "spam"),
    ("Security check required", "spam"),
    ("Account verification", "spam"),
    ("Payment authorization", "spam"),
    ("Account security", "spam"),
    ("Payment verification", "spam"),
    ("Account access", "spam"),

    # Events examples
    ("Conference registration", "events"),
    ("Webinar invitation", "events"),
    ("Event schedule update", "events"),
    ("Workshop confirmation", "events"),
    ("Seminar details", "events"),
    ("Event reminder", "events"),
    ("Conference agenda", "events"),
    ("Workshop materials", "events"),
    ("Event feedback request", "events"),
    ("Virtual event login", "events"),
    ("Event cancellation", "events"),
    ("Venue change notice", "events"),
    ("Speaker announcement", "events"),
    ("Registration confirmation", "events"),
    ("Schedule changes", "events"),
    ("Materials download", "events"),
    ("Networking session", "events"),
    ("Breakout rooms", "events"),
    ("Q&A session", "events"),
    ("Panel discussion", "events"),
    ("Keynote speaker", "events"),
    ("Workshop materials", "events"),
    ("Networking guide", "events"),
    ("Technical requirements", "events"),
    ("Event check-in", "events")
] 